config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  root to: 'home#index'
  resources :carriers, only: [:index, :show, :new, :create ,:edit, :update]
  resources :vehicles, only: [:new, :create]
  resources :prices, only: [:index]

  resources :carriers, only: [:show] do
    resources :vehicles, only: [:index, :show]
    resources :prices, only: [:new, :create]
    resources :deadlines, only: [:new, :create]
    resources :orders, only:[:show]
    patch 'activate', on: :member
    patch 'desactivate', on: :member
  end

  resources :orders, only: [:index, :new, :create,:update] do
    patch 'deny', on: :member
    patch 'accept', on: :member
    patch 'in_transit', on: :member
    patch 'delivered', on: :member
    resources :delivery_updates, only: [:show, :create]
    get 'search', on: :collection
  end

  resources :budgets, only:[:index, :create, :show] 

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index
  @carrier = Carrier.all
end

end

app/views/home/index.html.erb
<section id = 'home'>
  <h2>Olá, Bem vindo à CC-Delivery</h2>
  <% if admin_signed_in? || user_signed_in? %>
    <div>
      <%= link_to('Lista de Transportadoras', carriers_path) %>
    <div>
  <% end%>
</section>


<section id = 'query'>
  <h4>Rastreie seu pedido:</h4>
    <%=form_with(url: search_orders_path, method: :get) do |f| %>
    <%= f.label :query, 'Código de rastreio' %>:
    <%= f.text_field :query%>
    <%= f.submit 'Buscar' %>
    <% end%>
</section>