config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  root to: 'home#index'
  resources :carriers, only: [:index, :show, :new, :create ,:edit, :update]
  resources :vehicles, only: [:new, :create]
  resources :prices, only: [:index]

  resources :carriers, only: [:show] do
    resources :vehicles, only: [:index, :show]
    resources :prices, only: [:new, :create]
    resources :deadlines, only: [:new, :create]
    resources :orders, only:[:show]
    patch 'activate', on: :member
    patch 'desactivate', on: :member
  end

  resources :orders, only: [:index, :new, :create,:update] do
    patch 'deny', on: :member
    patch 'accept', on: :member
    patch 'in_transit', on: :member
    patch 'delivered', on: :member
    resources :delivery_updates, only: [:show, :create]
    get 'search', on: :collection
  end

  resources :budgets, only:[:index, :create, :show] 

end

app/models/order.rb
class Order < ApplicationRecord
  enum status: {denied:0, pending:10, accepted:20, in_transit:30, delivered:40}
  belongs_to :carrier
  belongs_to :vehicle, optional: true
  has_many :delivery_updates

  validates :vehicle_id, presence: true, unless: :enum_validation
  validates :status, :size, :weight, :customar_name, :customer_adress,:distance,:track_number, :product_number,:delivery_deadline, presence: true
  validates :size, :weight, :distance, numericality: { greater_than: -1 }
  before_validation :generate_track_number, on: :create
  before_validation :final_price
  before_validation :deadline

  private

  def generate_track_number
    self.track_number = SecureRandom.alphanumeric(15).upcase
  end

  def final_price
    price = self.carrier.prices.where('size_min < ? and  size_max > ?', self.size,self.size ) && self.carrier.prices.where('weight_min < ? and  weight_max > ?', self.weight,self.weight )
    self.total_price = self.distance * price.first.km_value
  end

  def deadline
    deadline =  self.carrier.deadlines.where('km_min < ? and  km_max > ?', self.distance,self.distance )
    self.delivery_deadline = deadline.first.km_time
  end

  def enum_validation
    self.status == 'pending' ||  self.status == 'denied'  
  end


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    if admin_signed_in?
      @orders = Order.all
    elsif user_signed_in?
      @orders = current_user.carrier.orders
    else
      redirect_to root_path, notice:'Erro! Página não encontrada :('
    end
  end

  def new
    @carriers = Carrier.all
    @order = Order.new
  end

 
  def create
    @carriers = Carrier.all
    @order = Order.new(order_params)
    if @order.save == true
      redirect_to carrier_order_path(@order.carrier, @order) , notice: 'Pedido registrado com sucesso'
    else 
      flash.now[:notice] = 'Não foi possível criar a ordem de serviço'
      render 'new'
    end
  end

  def show
    @delivery_update = DeliveryUpdate.new
    @order = Order.find(params[:id])
    @delivery_updates = @order.delivery_updates
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(accept_order)
      return redirect_to carrier_order_path(@order), notice:'Ordem atualizada com sucesso'
    else
      flash.now[:notice] = 'Não foi possível atualizar a ordem de serviço'
      render 'show'
    end
  end


  def accept
    @order =  Order.find(params[:id])
    if @order.accepted!
    redirect_to carrier_order_path(@order.id), notice: 'Ordem atualizada com sucesso'
    else 
      redirect_to carrier_order_path(@order.id), notice: 'Por favor, selecione um veiculo'
    end
  end
  
  def deny
    @order =  Order.find(params[:id])
    @order.denied!
    redirect_to carrier_order_path(@order.id), notice: 'Ordem atualizada com sucesso'
  end
  
  def in_transit
    @order =  Order.find(params[:id])
    @order.in_transit!
    redirect_to carrier_order_path(@order.id), notice: 'Ordem atualizada com sucesso'
  end
  
  def delivered
    @order =  Order.find(params[:id])
    @order.delivered!
    redirect_to carrier_order_path(@order.id), notice: 'Ordem atualizada com sucesso'
  end

  def search
    @code = params["query"]
    @order = Order.find_by(track_number:@code)
    if @order.present?
      @delivery_update = @order.delivery_updates
    end
  end



private
  def order_params
    params.require(:order).permit(:carrier_id, :vehicle_id, 
      :size,:weight,:customar_name,:customer_adress,:derparture_adress,
      :distance, :track_number, :status, :product_number, :total_price,
      :delivery_deadline)
  end

def accept_order
  params.require(:order).permit(:vehicle_id, :status)
end

#cálculo de volume e preço da entrega
def budget(altura,largura,profundidade,peso,route_km)
  volume = altura * largura * profundidade
  @prices = Price.where('size_min < ? and  size_max > ?', volume,volume )
  final_price = @prices.each do |b|
    b.km_value * route_km
  end
end


end

app/views/orders/index.html.erb
<h1>Lista de ordens de serviço:</h1>
<% if admin_signed_in? %>
  <div>
    <%= link_to 'Criar ordem de serviço', new_order_path %>
  </div>
<% end %>

<% if @orders.any?%>
    <table>
      <thead>
        <tr>
          <th>Código de rastreio: </th>
          <th> Transportadora: </th>
          <th> Status: </th>
        </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
            <tr>
            <td> <%= link_to order.track_number, carrier_order_path(order.carrier, order)  %></td>
            <td> <%= order.carrier.brand_name %> 
            <td> <%= Order.human_attribute_name(order.status) %> 
           </tr>
          <% end %>
        <tbody>
      </table>
<% else %>
  <p> Não existem ordens de serviço cadastrados.</p>
<% end %>

<% if user_signed_in? %>
<%= link_to 'Voltar', carrier_path(current_user.carrier)  %>
<% end %>

app/views/orders/new.html.erb
<h1> Criar ordem de serviço </h1>


<% if(@order.errors.any?) %>
  <p>Verifique os erros abaixo:</p>
  <ul>
    <% @order.errors.full_messages.each do |msg| %>
      <li> <%= msg %> </li>
      <% end %>
  </ul>
<% end %>



<%= form_with(model: @order ) do |f| %>

  <div>
  <%= f.label :carrier_id %>:
  <%= f.collection_select :carrier_id, @carriers, :id, :brand_name %>
  </div>

  <div>
  <%= f.label :customar_name  %>:
  <%= f.text_field :customar_name %>
  </div>

  <div>
  <%= f.label :derparture_adress %>:
  <%= f.text_field :derparture_adress %>
  </div>

  <div>
  <%= f.label :customer_adress %>:
  <%= f.text_field :customer_adress %>
  </div>

  <div>
  <%= f.label :distance %>:
  <%= f.number_field :distance %>
  </div>

  <div>
  <%= f.label :weight %>:
  <%= f.number_field :weight, step: 0.1 %>
  </div>

  <div>
  <%= f.label :size %>:
  <%= f.number_field :size, step: 0.1 %>
  </div>

  <div>
  <%= f.label :product_number %>:
  <%= f.text_field :product_number %>
  </div>

  <div>
  <%= f.submit 'Cadastrar' %>
  </div>
<% end%>

app/views/orders/search.html.erb
<h2>Resultado da busca por: <%= @code %> </h2>

<% if @order.present? %>
  <dt> <strong> Nome do cliente: </strong> </dt>
  <dd> <%= @order.customar_name  %>  </dd>
  <dt><strong> Código do produto: </strong> </dt>
  <dd> <%= @order.product_number  %>  </dd>
  <dt> <strong> Endereço de entrega: </strong> </dt>
  <dd> <%= @order.customer_adress  %>  </dd>
   <dt> <strong> Transportadora: </strong> </dt>
  <dd> <%= @order.carrier.brand_name  %>  </dd>
  <dt> <strong> Prazo de entrega: </strong> </dt>
  <dd> <%= @order.delivery_deadline  %>  Dia(s) úteis </dd>
  <dt> <strong> Valor do frete: </strong> </dt>
  <dd> <%=  number_to_currency(@order.total_price)  %> </dd>
  <dt> <strong> Código de rastreio: </strong> </dt>
  <dd> <%= @order.track_number  %></dd>

<section id = 'delivery updates'>
  <p><strong> Situação da entrega: </strong></p>
    <%if @delivery_update.present? %>
      <table>
        <thead>
        <tr>
          <th> | Local: |</th>
          <th> | Descrição: |</th>
          <th> | Horário de atualização: | </th>
        </tr>
        </thead>
        <tbody>
          <% @delivery_update.each do |update| %>
            <tr>
            <td> | <%= update.coord_position %> | </td>
            <td> | <%= update.delivery_description %> | </td>
            <td> | <%= I18n.l update.created_at, format: :long %> | </td>
          </tr>
          <% end %>
        <tbody>
      </table>
    <% else%>
    </p> Não existem atualizações de entrega para este pedido.</p>
    <% end %>
</section>
<%else%>
    <p> Não foi encontrado nenhum pedido com este código </p>
<% end %>


<section id = 'query'>
  <h4>Novo rastreio:</h4>
    <%=form_with(url: search_orders_path, method: :get) do |f| %>
    <%= f.label :query, 'Código de rastreio' %>:
    <%= f.text_field :query%>
    <%= f.submit 'Buscar' %>
    <% end%>
</section>

app/views/orders/show.html.erb
<section id = 'pending orders'>
<% if @order.pending? %>
  <h2>Ordem de serviço pendente: <%= @order.track_number %></h2>
  <div>
    <dl>
        <dt> <strong> Nome do cliente: </strong> </dt>
        <dd> <%= @order.customar_name  %>  </dd>
        <dt> <strong> Código do produto: </strong> </dt>
        <dd> <%= @order.product_number  %>  </dd>
        <dt> <strong> Endereço de retirada: </strong> </dt>
        <dd> <%= @order.derparture_adress  %>  </dd>
        <dt> <strong> Endereço de entrega: </strong> </dt>
        <dd> <%= @order.customer_adress  %>  </dd>
        <dt> <strong> Distância: </strong> </dt>
        <dd> <%= @order.distance  %> Km   </dd>
        <dt> <strong> Peso: </strong> </dt>
        <dd> <%= @order.weight  %> Kg </dd>
        <dt> <strong> Prazo de entrega: </strong> </dt>
        <dd> <%= @order.delivery_deadline  %>  Dia(s) </dd>
        <dt> <strong> Valor da entrega: </strong> </dt>
        <dd> <%=  number_to_currency(@order.total_price)  %> </dd>
        <dt> <strong> Código de rastreio: </strong> </dt>
        <dd> <%= @order.track_number  %></dd>
        <dt> <strong> Status: <strong> </dt>
        <dd> <%= Order.human_attribute_name(@order.status) %> </dd>
    </dl>
  </div>  
  <div>
    <%= form_with(model:@order) do |f| %>
      <%= f.label :vehicle_id %>
      <%= f.collection_select :vehicle_id, @order.carrier.vehicles, :id, :full_description %>
      <%= f.submit 'Selecionar veículo' %>
    <% end%>
  </div>  
  <p> Deseja aceitar a ordem de serviço? </p>
  <%= button_to "Aceitar", accept_order_path, {method: 'patch'} %> <br/> 
  <%= button_to "Recusar",  deny_order_path, {method: 'patch'} %>
<% end%>
</section>

<section id = 'Actual orders'>
<% if @order.accepted? || @order.in_transit? %>
  <h2>Ordens de serviço: <%= @order.track_number %></h2>
  <dl>
      <dt> <strong> Nome do cliente: </strong> </dt>
      <dd>  <%= @order.customar_name  %>  </dd>
      <dt><strong> Código do produto: </strong> </dt>
      <dd> <%= @order.product_number  %>  </dd>
      <dt><strong> Endereço de retirada: </strong> </dt>
      <dd> <%= @order.derparture_adress  %>  </dd>
      <dt> <strong> Endereço de entrega: </strong> </dt>
      <dd> <%= @order.customer_adress  %>  </dd>
      <dt> <strong> Distância: </strong> </dt>
      <dd> <%= @order.distance  %> Km   </dd>
      <dt> <strong> Peso: </strong> </dt>
      <dd> <%= @order.weight  %> Kg </dd>
      <dt> <strong> Prazo de entrega: </strong> </dt>
      <dd> <%= @order.delivery_deadline  %>  Dia(s) </dd>
      <dt> <strong> Veículo designado: </strong> </dt>
      <dd> <%= @order.vehicle.full_description %>  </dd>
      <dt> <strong> Valor da entrega: </strong> </dt>
      <dd> <%=  number_to_currency(@order.total_price)  %> </dd>
      <dt> <strong> Código de rastreio: </strong> </dt>
      <dd> <%= @order.track_number  %></dd>
      <dt> <strong> Status: <strong> </dt>
      <dd> <%= Order.human_attribute_name(@order.status) %> </dd>
  </dl>
  <p> Atualizar ordem de serviço </p>
  <% if @order.accepted? %>
    <%= button_to "Em transito", in_transit_order_path, {method: 'patch'} %>
  <% elsif @order.in_transit? %>
    <%= button_to "Entregue", delivered_order_path, {method: 'patch'} %>
  <% end %>
<% end%>
</section>

<section id = 'Finished Orders'>
<% if @order.delivered?%>
  <h2>Ordem de serviço: <%= @order.track_number %></h2>
  <dl>
      <dt> <strong> Nome do cliente: </strong> </dt>
      <dd> <%= @order.customar_name  %>  </dd>
      <dt><strong> Código do produto: </strong> </dt>
      <dd> <%= @order.product_number  %>  </dd>
      <dt><strong> Endereço de retirada: </strong> </dt>
      <dd> <%= @order.derparture_adress  %>  </dd>
      <dt> <strong> Endereço de entrega: </strong> </dt>
      <dd> <%= @order.customer_adress  %>  </dd>
      <dt> <strong> Distância: </strong> </dt>
      <dd> <%= @order.distance  %> Km   </dd>
      <dt> <strong> Peso: </strong> </dt>
      <dd> <%= @order.weight  %> Kg </dd>
      <dt> <strong> Prazo de entrega: </strong> </dt>
      <dd> <%= @order.delivery_deadline  %>  Dia(s) </dd>
      <dt> <strong> Veículo designado: </strong> </dt>
      <dd> <%= @order.vehicle.full_description %>  </dd>
      <dt> <strong> Valor da entrega: </strong> </dt>
      <dd> <%=  number_to_currency(@order.total_price)  %> </dd>
      <dt> <strong> Código de rastreio: </strong> </dt>
      <dd> <%= @order.track_number  %></dd>
      <dt> <strong> Status: <strong> </dt>
      <dd> <%= Order.human_attribute_name(@order.status) %> </dd>
  </dl>
<% end%>
</section>


<% if(@delivery_update.errors.any?) %>
  <p>Verifique os erros abaixo:</p>
  <ul>
    <% @delivery_update.errors.full_messages.each do |msg| %>
      <li> <%= msg %> </li>
      <% end %>
  </ul>
<% end %>

<section id = 'delivery updates'>
  <p> Situação da entrega:</p>
    <%if @delivery_updates.present? %>
      <table>
        <thead>
        <tr>
          <th> | Local: |</th>
          <th> | Descrição: |</th>
          <th> | Horário de atualização: | </th>
        </tr>
        </thead>
        <tbody>
          <% @delivery_updates.each do |update| %>
            <tr>
            <td> | <%= update.coord_position %> | </td>
            <td> | <%= update.delivery_description %> | </td>
            <td> | <%= I18n.l update.created_at, format: :long %> | </td>
          </tr>
          <% end %>
        <tbody>
      </table>
    <% else%>
    </p> Não existem atualizações de entrega para este pedido.</p>
    <% end %>
</section>

<section id = 'route updates'>
<% if @order.pending? == false && @order.delivered? == false %>
  <p> Atualizar status de entrega: </p>

  <%= form_with(model: [@order, @delivery_update]) do |f| %>
    <div>
      <%= f.label :coord_position %>:
      <%= f.text_field :coord_position %>
    </div>
    <div>
      <%= f.label :delivery_description %>:
      <%= f.text_field :delivery_description %>
    </div>
    <div>

    </div>
    <%= f.submit 'Atualizar' %>
  <% end%>

<% end %>
</section>