config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  root to: 'home#index'
  resources :carriers, only: [:index, :show, :new, :create ,:edit, :update]
  resources :vehicles, only: [:new, :create]
  resources :prices, only: [:index]

  resources :carriers, only: [:show] do
    resources :vehicles, only: [:index, :show]
    resources :prices, only: [:new, :create]
    resources :deadlines, only: [:new, :create]
    resources :orders, only:[:show]
    patch 'activate', on: :member
    patch 'desactivate', on: :member
  end

  resources :orders, only: [:index, :new, :create,:update] do
    patch 'deny', on: :member
    patch 'accept', on: :member
    patch 'in_transit', on: :member
    patch 'delivered', on: :member
    resources :delivery_updates, only: [:show, :create]
    get 'search', on: :collection
  end

  resources :budgets, only:[:index, :create, :show] 

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CcDelivery</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <header>
      <h1> CC-Delivery </h1>
      <nav>
        <%= link_to 'Página Principal', root_path %> | 

      <% if user_signed_in? || admin_signed_in? %>
          <% if user_signed_in? %>
              <%= current_user.email %>
              <%= button_to 'Sair', destroy_user_session_path, method: :delete %>
          <% elsif admin_signed_in? %>
              <%= link_to 'Tabelas de preços', prices_path %> |
              <%= link_to 'Consultar orçamento', budgets_path%> |
              <%= link_to 'Ordens de serviço', orders_path %> |
              <%= link_to('Cadastrar Transportadora', new_carrier_path)%> |
              <%= current_admin.email %>
              <%= button_to 'Sair', destroy_admin_session_path, method: :delete %>
          <% end %>
      <% else %>
          <%= link_to 'Entrar',  new_user_session_path %> |
          <%= link_to 'Trabalha conosco? Clique aqui',  new_admin_session_path %> | <br/>
      <% end %>

      </nav>
    </header>
    <main>
  <div style = "margin:10px 0px" >
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>
    <%= yield %>
  </body>
</html>